animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "The first animal at 1 is %s" % animals[1]
print "The 3rd animal is %s" % animals[2]
print "The first animal is %s" % animals[0]
print "The animal at 3 is %s" % animals[3]
print "The 5th animal is %s" % animals[4]
print "The animal at 2 is %s" % animals[2]
print "The 6th animal is %s" % animals[5]
print "The animal at 4 is %s" % animals[4]
